name: MaintainerCheck
description: 'Checks if a given username belongs is part of a maintainers list and fails when it is not'
inputs:
  username:
    description: 'Username to be checked'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        MAINTAINERS=${{ env.MAINTAINERS }}
        USERNAME=${{ inputs.username }}
        if [[ "$MAINTAINERS" == *"$USERNAME"* ]]; then
          echo "${USERNAME} is a maintainer"
          exit 0
        fi
        echo "${USERNAME} is not a maintainer"
        exit 1
      with:
        MAINTAINERS: "tzneal,spring1843,ellistarn,akestner,bwagner5,billrayburn,suket22,njtran,chrisnegus,jonathan-innis,rtripat,engedaam"
