name: ApprovalComment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
    if: github.repository == 'spring1843/karpenter' && github.event.review.state == 'approved' && startsWith(github.event.review.body ,'/karpenter snapshot')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - uses: ./.github/actions/maintainer-check
        with:
          username: ${{ github.event.review.sender }}
      - name: Save info about the review comment as an artifact for other workflows that run on workflow_run to download them
        run: |
          mkdir -p /tmp/artifacts
          echo ${{ github.event.pull_request.number }} >> /tmp/artifacts/metadata.txt
          echo ${{ github.event.review.commit_id }} >> /tmp/artifacts/metadata.txt
          cat /tmp/artifacts/metadata.txt
      - uses: ./.github/actions/upload-artifact
