name: ApprovalComment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  approval-comment:
    if: github.repository == 'spring1843/karpenter' && contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/karpenter snapshot'))

    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  - name: Check to see if the comment is from a trusted user
      run: |
        SITE_ADMIN=${{ github.event.comment.user.site_admin }}
        if [[ "$SITE_ADMIN" != "true"]]; then
          echo "${SITE_ADMIN} not a  set to true"
          exit 1
        fi

      - name: Save info about the review comment as an artifact for other workflows that run on workflow_run to download them
        run: |
          mkdir -p /tmp/artifacts
          echo ${{ github.event.pull_request.number }} >> /tmp/artifacts/metadata.txt
          echo ${{ github.event.review.commit_id }} >> /tmp/artifacts/metadata.txt
          cat /tmp/artifacts/metadata.txt
      - uses: ./.github/actions/upload-artifact
